executor: go-machine
steps:
  - check-branch-name
  - setup-go
  - checkout
  - go_test:
      log_dir: "/tmp/testlogs"
      save_cache: true
  - store_artifacts:
      path: test-results
  - store_test_results:
      path: test-results
  - store_artifacts:
      path: "/tmp/testlogs"
